### ISSUE TITLE
Suggestion: use `JSON` for certain Zod Types to allow for semi-structured data

### ISSUE THREAD

**Issue by TillaTheHun0** [minodisk/zoq#1]
This is very cool idea. Thanks for sharing.

I noticed some Zod types are currently implemented such that attempting to convert them results in an error ie. `ZodUnion`, `ZodDiscriminatedUnion`, `ZodIntersection`, and `ZodAny`.

Per [GCP BigQuery docs](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json#loading_semi-structured_json_data), BigQuery does support loading semi-structured data by specifying the field to be type `JSON`. That seems to fit perfectly for this use case and would allow creating a BigQuery schema from a Zod schema that uses any of those types, without throwing an error. If folks still wanted this to throw, you could allow passing `options` object with `allowSemiStructuredTypes` or whatever name makes most sense for the goals of this tool.

Thoughts?

**Comment by minodisk** [comment]
Looks good. `ZodUnion`, `ZodDiscriminatedUnion`, `ZodIntersection`, and `ZodAny` are just errors because I didn't think there was any use for them, and I don't think it is necessary to make errors.
So I think it would be good to make these the JSON type in BQ.

**Comment by minodisk** [comment]
I made a PR #2. This is what you are proposing, right?

**Comment by minodisk** [comment]
@TillaTheHun0 ping

**Comment by TillaTheHun0** [comment]
Sorry for the delay.

Very cool, I was going to take a stab at a PR, if you thought it was a good suggestion, but looks like you've already done that 😄 .

I haven't tested it or anything, but that PR looks kosher to me! Nice work!

**Comment by minodisk** [comment]
@TillaTheHun0 
Thanks for the great suggestion.
I merged #2 and published as v0.0.7. Please give it a try 😉 .

**Comment by TillaTheHun0** [comment]
Very cool. Feel free to close this issue. Thanks again.
